### ISSUE TITLE
Python 3.10.4 proxy_checker didn't installed.

### ISSUE THREAD

**Issue by mustafayilmazx** [StickySitch/Basic_Proxy_Scraper_GUI#1]
`PS C:\Users\xxx\Desktop> pip install proxy_checker
Collecting proxy_checker
  Downloading proxy_checker-0.6-py3-none-any.whl (4.6 kB)
Collecting pycurl
  Downloading pycurl-7.45.1.tar.gz (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.9/233.9 kB 1.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 10
  ╰─> [1 lines of output]
      Please specify --curl-dir=/path/to/built/libcurl
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by StickySitch** [comment]
> 

I appreciate your issue request! For some reason I have only been able to get the dependencies (PyCurl) working by manually installing using the wheel file provided here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycurl

I will look at a fix for this when home from work tonight. Again, I truly appreciate you taking the time to help make this project better.

**Comment by StickySitch** [comment]
Since this seems to be an issue with the PyCurl (common issue), I will be closing this issue. To deal with this issue you have two options:

1. Use the [wheel file](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycurl) to install PyCurl.
2. Download BasicProxyScaper.exe from the [releases section](https://github.com/StickySitch/Basic_Proxy_Scraper_GUI/releases)
